services:
  - type: web
    name: heiba-recruitment
    env: node
    plan: free
    rootDir: .  # Dies weist Render an, das Hauptverzeichnis zu verwenden
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: heiba-data
      mountPath: /data
      sizeGB: 1
