services:
  - type: web
    name: heiba-recruitment
    env: node
    plan: free
    rootDir: .  # Dies weist Render an, das Hauptverzeichnis zu verwenden
    buildCommand: yarn install && mkdir -p /opt/render/project/src && cp package.json /opt/render/project/src/ && yarn build
    startCommand: cd /opt/render/project/src && yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: heiba-data
      mountPath: /data
      sizeGB: 1
