services:
  - type: web
    name: heiba-recruitment
    env: node
    plan: free
    rootDir: .  # Dies weist Render an, das Hauptverzeichnis zu verwenden
    buildCommand: bash -c "yarn install && yarn build && mkdir -p /opt/render/project/src && cp -r .next node_modules package.json yarn.lock next.config.js public /opt/render/project/src/"
    startCommand: cd /opt/render/project/src && yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: heiba-data
      mountPath: /data
      sizeGB: 1
